### ISSUE TITLE
Chinese translation

### ISSUE THREAD

**Issue by freedombird9** [aredridel/how-to-read-code#3]
Hi Aria,

I find this article you wrote extremely enlightening and helpful. I really appreciate your effort. In order to let more people in China be able to read it, I translated your work into Chinese. It's here:

https://github.com/freedombird9/how-to-read-source-code

Thank you so much for sharing your insights.

**Comment by aredridel** [comment]
Oh neat!

**Comment by aredridel** [comment]
Thank you so much! Documented in https://github.com/aredridel/how-to-read-code/commit/71cf7fed22383b0134a2468ebe16aaedab79e4bb
