### ISSUE TITLE
What's the meaning of looking for composition and inheritance

### ISSUE THREAD

**Issue by jiegerl** [aredridel/how-to-read-code#5]
I don't quite understand the meaning of the sentence below.
> Is this made of parts I can recognize? Do those parts have names?

**Comment by aredridel** [comment]
Ooh, a concrete example, in PHP:

```php
class MyButton extends Widget {
   use TextualContent;
   use EventHandlers;

   public function onClick() {
      doThing();
   }
}
```

In this case, `TextualContent` and `EventHandlers` are what PHP calls traits — they are building blocks that can be included in other classes. If you're dissecting an unknown-unknown system, you might find evidence like this that hints that things are made of smaller pieces.

You might wonder what actually makes `onClick()` work — in this case, a good guess would be the `use EventHandlers` so you know what to read next.

Likewise, `extends Widget` is PHP for inheritance — part of this code is inherited from elsewhere, and that's where you'll have to read to find the rest.

**Comment by aredridel** [comment]
Thank you for asking the question!
